// Original data, inspired by classic tower sims, but not copied from any proprietary source.

export const ROOM = {
  LOBBY: "Lobby",
  ELEVATOR_SHAFT: "Elevator Shaft",
  STAIRS: "Stairs",
  APARTMENT: "Apartment",
  CONDO: "Condo",
  OFFICE: "Office",
  FASTFOOD: "Fast Food",
  RESTAURANT: "Restaurant",
  RETAIL: "Retail",
  HOTEL: "Hotel Room",
  SUITE: "Suite",
  THEATER: "Movie Theater",
  PARTY: "Party Room",
  SECURITY: "Security",
  MEDICAL: "Medical",
  RECYCLE: "Recycling",
  PARKING: "Parking",
  JANITOR: "Janitorial",
  METRO: "Metro Station",
};

export const RoomTypes = {
  [ROOM.LOBBY]: {
    key: ROOM.LOBBY,
    size: { w: 10, h: 1 },
    buildCost: 8000,
    maintPerDay: 80,
    noise: 1,
    traffic: 2,
    happiness: +1,
    unlockStars: 1,
    rules: { groundOnly: true, unique: true }
  },

  [ROOM.ELEVATOR_SHAFT]: {
    key: ROOM.ELEVATOR_SHAFT,
    size: { w: 1, h: 1 },
    buildCost: 1200,
    maintPerDay: 6,
    noise: 0,
    traffic: 0,
    happiness: 0,
    unlockStars: 1,
    rules: { shaft: true }
  },

  [ROOM.STAIRS]: {
    key: ROOM.STAIRS,
    size: { w: 1, h: 1 },
    buildCost: 700,
    maintPerDay: 4,
    noise: 0,
    traffic: 0,
    happiness: 0,
    unlockStars: 1,
    rules: { stairs: true }
  },

  [ROOM.APARTMENT]: {
    key: ROOM.APARTMENT,
    size: { w: 6, h: 1 },
    buildCost: 6000,
    maintPerDay: 45,
    noise: 1,
    traffic: 2,
    happiness: +2,
    unlockStars: 1,
    category: "Residential",
    capacity: 24,
  },

  [ROOM.CONDO]: {
    key: ROOM.CONDO,
    size: { w: 8, h: 1 },
    buildCost: 11000,
    maintPerDay: 60,
    noise: 1,
    traffic: 2,
    happiness: +3,
    unlockStars: 2,
    category: "Residential",
    capacity: 34,
  },

  [ROOM.OFFICE]: {
    key: ROOM.OFFICE,
    size: { w: 10, h: 1 },
    buildCost: 14000,
    maintPerDay: 100,
    noise: 1,
    traffic: 5,
    happiness: +0,
    unlockStars: 2,
    category: "Commercial",
    workers: 60,
  },

  [ROOM.FASTFOOD]: {
    key: ROOM.FASTFOOD,
    size: { w: 6, h: 1 },
    buildCost: 9000,
    maintPerDay: 75,
    noise: 2,
    traffic: 4,
    happiness: +1,
    unlockStars: 2,
    category: "Commercial",
  },

  [ROOM.RESTAURANT]: {
    key: ROOM.RESTAURANT,
    size: { w: 8, h: 1 },
    buildCost: 15000,
    maintPerDay: 120,
    noise: 2,
    traffic: 4,
    happiness: +2,
    unlockStars: 2,
    category: "Commercial",
  },

  [ROOM.RETAIL]: {
    key: ROOM.RETAIL,
    size: { w: 6, h: 1 },
    buildCost: 10000,
    maintPerDay: 90,
    noise: 1,
    traffic: 4,
    happiness: +1,
    unlockStars: 2,
    category: "Commercial",
  },

  [ROOM.HOTEL]: {
    key: ROOM.HOTEL,
    size: { w: 6, h: 1 },
    buildCost: 12000,
    maintPerDay: 95,
    noise: 1,
    traffic: 2,
    happiness: +2,
    unlockStars: 3,
    category: "Hotel",
    capacity: 18,
    needsCleaning: true,
  },

  [ROOM.SUITE]: {
    key: ROOM.SUITE,
    size: { w: 8, h: 1 },
    buildCost: 22000,
    maintPerDay: 160,
    noise: 1,
    traffic: 2,
    happiness: +3,
    unlockStars: 3,
    category: "Hotel",
    capacity: 28,
    needsCleaning: true,
  },

  [ROOM.SECURITY]: {
    key: ROOM.SECURITY,
    size: { w: 4, h: 1 },
    buildCost: 8000,
    maintPerDay: 85,
    noise: 0,
    traffic: 1,
    happiness: +1,
    unlockStars: 3,
    category: "Services",
    coverage: 18,
  },

  [ROOM.MEDICAL]: {
    key: ROOM.MEDICAL,
    size: { w: 4, h: 1 },
    buildCost: 9000,
    maintPerDay: 90,
    noise: 0,
    traffic: 1,
    happiness: +1,
    unlockStars: 3,
    category: "Services",
    coverage: 18,
  },

  [ROOM.THEATER]: {
    key: ROOM.THEATER,
    size: { w: 10, h: 1 },
    buildCost: 26000,
    maintPerDay: 190,
    noise: 4,
    traffic: 6,
    happiness: +3,
    unlockStars: 3,
    category: "Entertainment",
  },

  [ROOM.PARTY]: {
    key: ROOM.PARTY,
    size: { w: 8, h: 1 },
    buildCost: 18000,
    maintPerDay: 140,
    noise: 5,
    traffic: 5,
    happiness: +2,
    unlockStars: 3,
    category: "Entertainment",
  },

  [ROOM.JANITOR]: {
    key: ROOM.JANITOR,
    size: { w: 4, h: 1 },
    buildCost: 7000,
    maintPerDay: 85,
    noise: 0,
    traffic: 1,
    happiness: +1,
    unlockStars: 2,
    category: "Services",
    coverage: 14,
  },

  [ROOM.PARKING]: {
    key: ROOM.PARKING,
    size: { w: 10, h: 1 },
    buildCost: 16000,
    maintPerDay: 110,
    noise: 1,
    traffic: 4,
    happiness: +1,
    unlockStars: 1,
    category: "Services",
    rules: { basementOnly: true }
  },

  [ROOM.RECYCLE]: {
    key: ROOM.RECYCLE,
    size: { w: 6, h: 1 },
    buildCost: 14000,
    maintPerDay: 120,
    noise: 1,
    traffic: 1,
    happiness: +2,
    unlockStars: 4,
    category: "Services",
    rules: { basementOk: true }
  },

  [ROOM.METRO]: {
    key: ROOM.METRO,
    size: { w: 10, h: 1 },
    buildCost: 45000,
    maintPerDay: 260,
    noise: 2,
    traffic: 10,
    happiness: +3,
    unlockStars: 4,
    category: "Infrastructure",
    rules: { basementOnly: true, unique: true }
  },
};

export const BuildMenu = [
  ROOM.LOBBY,
  ROOM.ELEVATOR_SHAFT,
  ROOM.STAIRS,
  ROOM.APARTMENT,
  ROOM.CONDO,
  ROOM.OFFICE,
  ROOM.RETAIL,
  ROOM.FASTFOOD,
  ROOM.RESTAURANT,
  ROOM.JANITOR,
  ROOM.PARKING,
  ROOM.HOTEL,
  ROOM.SUITE,
  ROOM.SECURITY,
  ROOM.MEDICAL,
  ROOM.THEATER,
  ROOM.PARTY,
  ROOM.RECYCLE,
  ROOM.METRO,
];
