import type { RoomCategory, RoomType } from "./types";

export const CATEGORY_ORDER: readonly RoomCategory[] = [
  "Infrastructure",
  "Residential",
  "Commercial",
  "Hotel",
  "Entertainment",
  "Services",
] as const;

export const ROOM_TYPES: Readonly<Record<string, RoomType>> = {
  lobby: {
    id: "lobby",
    name: "Lobby",
    category: "Infrastructure",
    width: 6,
    cost: 25000,
    maintenance: 80,
    revenue: 0,
    noise: 1,
    traffic: 10,
    happiness: 2,
    buildTime: 120,
    capacity: 0,
    unlock: 1,
    rules: { groundOnly: true },
  },
  stairs: {
    id: "stairs",
    name: "Stairs",
    category: "Infrastructure",
    width: 1,
    cost: 4000,
    maintenance: 10,
    revenue: 0,
    noise: 0,
    traffic: 2,
    happiness: 1,
    buildTime: 60,
    capacity: 0,
    unlock: 1,
    rules: {},
    shaft: true,
    elevatorType: "stairs",
  },
  elevator_standard: {
    id: "elevator_standard",
    name: "Standard Elevator",
    category: "Infrastructure",
    width: 1,
    cost: 12000,
    maintenance: 35,
    revenue: 0,
    noise: 1,
    traffic: 2,
    happiness: 1,
    buildTime: 90,
    capacity: 10,
    unlock: 1,
    rules: {},
    shaft: true,
    elevatorType: "standard",
  },
  elevator_express: {
    id: "elevator_express",
    name: "Express Elevator",
    category: "Infrastructure",
    width: 1,
    cost: 20000,
    maintenance: 55,
    revenue: 0,
    noise: 1,
    traffic: 2,
    happiness: 1,
    buildTime: 120,
    capacity: 12,
    unlock: 3,
    rules: { minFloors: 6 },
    shaft: true,
    elevatorType: "express",
  },
  elevator_service: {
    id: "elevator_service",
    name: "Service Elevator",
    category: "Infrastructure",
    width: 1,
    cost: 16000,
    maintenance: 45,
    revenue: 0,
    noise: 1,
    traffic: 1,
    happiness: 0,
    buildTime: 100,
    capacity: 8,
    unlock: 3,
    rules: {},
    shaft: true,
    elevatorType: "service",
    staffOnly: true,
  },
  metro: {
    id: "metro",
    name: "Metro Station",
    category: "Infrastructure",
    width: 4,
    cost: 90000,
    maintenance: 160,
    revenue: 300,
    noise: 4,
    traffic: 14,
    happiness: 4,
    buildTime: 240,
    capacity: 0,
    unlock: 4,
    rules: { basementOnly: true },
  },
  condo: {
    id: "condo",
    name: "Condo",
    category: "Residential",
    width: 3,
    cost: 12000,
    maintenance: 20,
    revenue: 90,
    noise: 1,
    traffic: 4,
    happiness: 2,
    buildTime: 90,
    capacity: 6,
    unlock: 1,
  },
  apartment: {
    id: "apartment",
    name: "Apartment",
    category: "Residential",
    width: 4,
    cost: 18000,
    maintenance: 30,
    revenue: 120,
    noise: 2,
    traffic: 5,
    happiness: 1,
    buildTime: 120,
    capacity: 10,
    unlock: 1,
  },
  office: {
    id: "office",
    name: "Office",
    category: "Commercial",
    width: 5,
    cost: 26000,
    maintenance: 60,
    revenue: 220,
    noise: 2,
    traffic: 10,
    happiness: 1,
    buildTime: 150,
    capacity: 20,
    unlock: 2,
  },
  fast_food: {
    id: "fast_food",
    name: "Fast Food",
    category: "Commercial",
    width: 3,
    cost: 14000,
    maintenance: 40,
    revenue: 160,
    noise: 3,
    traffic: 8,
    happiness: 1,
    buildTime: 110,
    capacity: 0,
    unlock: 2,
  },
  restaurant: {
    id: "restaurant",
    name: "Restaurant",
    category: "Commercial",
    width: 4,
    cost: 22000,
    maintenance: 70,
    revenue: 240,
    noise: 3,
    traffic: 9,
    happiness: 2,
    buildTime: 140,
    capacity: 0,
    unlock: 2,
  },
  retail: {
    id: "retail",
    name: "Retail Shop",
    category: "Commercial",
    width: 3,
    cost: 16000,
    maintenance: 45,
    revenue: 180,
    noise: 2,
    traffic: 7,
    happiness: 1,
    buildTime: 110,
    capacity: 0,
    unlock: 2,
  },
  hotel: {
    id: "hotel",
    name: "Hotel Room",
    category: "Hotel",
    width: 3,
    cost: 24000,
    maintenance: 50,
    revenue: 200,
    noise: 1,
    traffic: 6,
    happiness: 2,
    buildTime: 130,
    capacity: 4,
    unlock: 3,
  },
  suite: {
    id: "suite",
    name: "Hotel Suite",
    category: "Hotel",
    width: 4,
    cost: 36000,
    maintenance: 80,
    revenue: 320,
    noise: 1,
    traffic: 6,
    happiness: 3,
    buildTime: 160,
    capacity: 6,
    unlock: 3,
  },
  theater: {
    id: "theater",
    name: "Movie Theater",
    category: "Entertainment",
    width: 5,
    cost: 28000,
    maintenance: 65,
    revenue: 220,
    noise: 5,
    traffic: 10,
    happiness: 3,
    buildTime: 150,
    capacity: 0,
    unlock: 3,
  },
  party: {
    id: "party",
    name: "Party Room",
    category: "Entertainment",
    width: 4,
    cost: 20000,
    maintenance: 55,
    revenue: 190,
    noise: 6,
    traffic: 9,
    happiness: 2,
    buildTime: 140,
    capacity: 0,
    unlock: 3,
  },
  security: {
    id: "security",
    name: "Security",
    category: "Services",
    width: 3,
    cost: 18000,
    maintenance: 45,
    revenue: 0,
    noise: 0,
    traffic: 3,
    happiness: 3,
    buildTime: 120,
    capacity: 0,
    unlock: 3,
  },
  medical: {
    id: "medical",
    name: "Medical",
    category: "Services",
    width: 3,
    cost: 20000,
    maintenance: 55,
    revenue: 0,
    noise: 1,
    traffic: 3,
    happiness: 3,
    buildTime: 130,
    capacity: 0,
    unlock: 3,
  },
  recycling: {
    id: "recycling",
    name: "Recycling",
    category: "Services",
    width: 4,
    cost: 30000,
    maintenance: 60,
    revenue: 40,
    noise: 2,
    traffic: 2,
    happiness: 2,
    buildTime: 150,
    capacity: 0,
    unlock: 4,
  },
  parking: {
    id: "parking",
    name: "Parking",
    category: "Services",
    width: 5,
    cost: 26000,
    maintenance: 40,
    revenue: 140,
    noise: 2,
    traffic: 5,
    happiness: 1,
    buildTime: 140,
    capacity: 0,
    unlock: 2,
  },
  janitorial: {
    id: "janitorial",
    name: "Janitorial",
    category: "Services",
    width: 3,
    cost: 16000,
    maintenance: 40,
    revenue: 0,
    noise: 1,
    traffic: 2,
    happiness: 3,
    buildTime: 120,
    capacity: 0,
    unlock: 2,
  },
} as const;
