import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage({ viewport: { width: 960, height: 760 }, deviceScaleFactor: 2 });
p.on("pageerror", (e) => console.error("PAGE ERROR:", e.message));
await p.goto("http://localhost:4173/preview.html", { waitUntil: "networkidle" });
await p.waitForFunction(() => window.previewReady === true, null, { timeout: 8000 });
await p.waitForTimeout(700);
await p.screenshot({ path: "docs/screenshots/preview-rooms.png", fullPage: true });
console.log("captured preview-rooms");
await b.close();
